# Generated by Django 4.2.4 on 2024-03-20 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse', '0007_grossesse_grossesse_forfait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_rename_timestamp_note_created_at_note_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='note_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grossesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grossesse.grossesse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
