# Generated by Django 4.2.4 on 2024-01-31 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grossesse', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('frequence', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=50)),
                ('periode', models.CharField(max_length=50)),
                ('unite_de_temps', models.CharField(max_length=50)),
                ('start_date_forfait', models.DateField()),
                ('end_date_forfait', models.DateField()),
                ('date_subscribe', models.DateField()),
                ('categories', models.CharField(default='standard')),
                ('Grossesse_forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grossesse.grossesse')),
                ('blog_forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.createblog')),
                ('user_forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
