# Generated by Django 4.2.4 on 2024-03-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forfait', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forfait',
            name='Grossesse_forfait',
        ),
        migrations.RemoveField(
            model_name='forfait',
            name='blog_forfait',
        ),
        migrations.AddField(
            model_name='forfait',
            name='appartenir_a',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartenira', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forfait',
            name='nb_grossesse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
