# Generated by Django 4.2.4 on 2024-01-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grossesse',
            old_name='user_id',
            new_name='user',
        ),
    ]
