# Generated by Django 4.2.4 on 2024-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse', '0003_informationgrossesse_delete_infogrossesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationgrossesse',
            name='id',
        ),
        migrations.AlterField(
            model_name='informationgrossesse',
            name='semaine',
            field=models.JSONField(primary_key=True, serialize=False),
        ),
    ]
