# Generated by Django 4.2.4 on 2024-02-23 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grossesse', '0004_remove_informationgrossesse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossesse',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grossesse',
            name='create_by',
            field=models.ForeignKey(default=1, null=True,on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grossesse',
            name='modify_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grossesse',
            name='modify_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
