# Generated by Django 4.2.4 on 2024-02-23 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grossesse', '0005_grossesse_create_at_grossesse_create_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grossesse',
            name='create_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grossesse',
            name='modify_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
