# Generated by Django 4.2.4 on 2024-02-19 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_rdv_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
