# Generated by Django 4.2.4 on 2024-02-26 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse', '0006_alter_grossesse_create_by_alter_grossesse_modify_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdv', '0004_rendezvous_delete_rdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('create_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now_add=True)),
                ('create_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crer_par', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.IntegerField()),
                ('reminder', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, default='null', upload_to='')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now_add=True)),
                ('create_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creer_par', to=settings.AUTH_USER_MODEL)),
                ('grossesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grossesse.grossesse')),
                ('modify_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_par', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
