# Generated by Django 4.2.4 on 2024-02-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0008_medecin_delete_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='profession',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rdv.medecin'),
        ),
    ]
