# Generated by Django 4.2.4 on 2024-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0009_remove_rendezvous_email_remove_rendezvous_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='weight',
        ),
    ]
